// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/about-variants/FounderStory.tsx": () => import("../components/mockups/about-variants/FounderStory.tsx"),
  "./components/mockups/about-variants/MissionStrip.tsx": () => import("../components/mockups/about-variants/MissionStrip.tsx"),
  "./components/mockups/about-variants/WhatMakesUsDifferent.tsx": () => import("../components/mockups/about-variants/WhatMakesUsDifferent.tsx"),
  "./components/mockups/dashboard-header/ClientFirst.tsx": () => import("../components/mockups/dashboard-header/ClientFirst.tsx"),
  "./components/mockups/dashboard-header/IconMark.tsx": () => import("../components/mockups/dashboard-header/IconMark.tsx"),
  "./components/mockups/dashboard-header/StyledText.tsx": () => import("../components/mockups/dashboard-header/StyledText.tsx"),
  "./components/mockups/login-variants/DarkHeader.tsx": () => import("../components/mockups/login-variants/DarkHeader.tsx"),
  "./components/mockups/login-variants/SmallerLogo.tsx": () => import("../components/mockups/login-variants/SmallerLogo.tsx"),
  "./components/mockups/login-variants/TextWordmark.tsx": () => import("../components/mockups/login-variants/TextWordmark.tsx"),
  "./components/mockups/website/Homepage.tsx": () => import("../components/mockups/website/Homepage.tsx")
};
