// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-variants/DarkHeader.tsx": () => import("../components/mockups/login-variants/DarkHeader.tsx"),
  "./components/mockups/login-variants/SmallerLogo.tsx": () => import("../components/mockups/login-variants/SmallerLogo.tsx"),
  "./components/mockups/login-variants/TextWordmark.tsx": () => import("../components/mockups/login-variants/TextWordmark.tsx")
};
